# Generated by Django 4.2.30 on 2026-04-29 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('media_type', models.CharField(choices=[('drama', '드라마'), ('movie', '영화'), ('youtube', '유튜브'), ('etc', '기타')], max_length=20)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.CharField(blank=True, choices=[('12', '관광지'), ('14', '문화시설'), ('15', '축제공연행사'), ('25', '여행코스'), ('28', '레포츠'), ('32', '숙박'), ('38', '쇼핑'), ('39', '음식점')], default='', max_length=5),
        ),
        migrations.AddField(
            model_name='place',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='MediaPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_description', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(default=1.0)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_places', to='places.media')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_places', to='places.place')),
            ],
            options={
                'unique_together': {('media', 'place')},
            },
        ),
    ]
