# Generated by Django 4.2.30 on 2026-05-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_media_place_category_place_is_verified_mediaplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('media_type', '미디어 유형'), ('genre', '장르'), ('place_type', '장소 유형')], max_length=20)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['category', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.AddField(
            model_name='media',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='media', to='places.tag'),
        ),
        migrations.AddField(
            model_name='place',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='places', to='places.tag'),
        ),
    ]
