# Generated by Django 4.2.30 on 2026-05-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_tag_media_tags_place_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaplace',
            name='ai_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mediaplace',
            name='status',
            field=models.CharField(choices=[('inferred', 'AI 추론'), ('admin_approved', '관리자 승인'), ('rejected', '반려'), ('quiz_confirmed', '퀴즈 확정')], default='inferred', max_length=20),
        ),
    ]
